version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - /usr/src/app/project/static
   command: /miniconda/envs/tatk-env/bin/gunicorn -w 2 -b :8080 project:app
 
 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web
 
 
